apiVersion: v1
kind: Config
clusters:
- name: dummy
  cluster:
    server: https://127.0.0.1:65535
contexts:
- name: dummy
  context:
    cluster: dummy
    user: dummy
current-context: dummy
users:
- name: dummy
  user: {}
