apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
  labels:
    name: ai-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      containers:
        - name: ai-server
          image: ai-orchestration
          env:
            - name: MISTRALAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mistral-secret
                  key: MISTRALAI_API_KEY
            - name: PUTER_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: puter-secret
                  key: PUTER_AUTH_TOKEN
            - name:  AI_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name:  database-secrets
                  key:  AI
            - name:  JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name:  jwt-secrets
                  key:  JWT_SECRET
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /api/ai/healthz
              port: 3000
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/ai/healthz
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 3000
              name: ai-server-port
