apiVersion: apps/v1
kind: Deployment
metadata:
  name:  auth-deployment
  labels:
    name:  auth-deployment
spec:
  replicas:  1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image:  auth
        imagePullPolicy: IfNotPresent
        name:  auth-container
        resources:
          requests:
            cpu: "250m"
            memory: "128M"
          limits:
            cpu: "500m"
            memory: "256M"
        livenessProbe:
          httpGet:
            path: /status/health
            port: 3000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  AUTH_MONGO_URI
          valueFrom:
            secretKeyRef:
              name:  database-secrets
              key:  AUTH
        - name:  GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name:  google-secrets
              key:  GOOGLE_CLIENT_ID
        - name:  GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name:  google-secrets
              key:  GOOGLE_CLIENT_SECRET
        - name:  JWT_SECRET
          valueFrom:
            secretKeyRef:
              name:  jwt-secrets
              key:  JWT_SECRET
        - name:  SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name:  session-secrets
              key:  SESSION_SECRET
        ports:
        - containerPort:  3000
          name:  auth-http